# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4030525eae7ef4a9bef7c730e94ffdd6f17a867a50b5b6bd8e622857924f633fe54e76d81ee3cfb2016135a3e6c25f0534775f550a9583c9f8b2e686fdf6ef1

test:
  secret_key_base: 19418136ae1f3ed6d0fffa161b0489fd0d8efd86e0f462054c57e050d3d796f2b029e48347039e9587c91cc5d3c67ec7bdd038ea0f44c41fe0b5cc59921171a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
